C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\camera.c -o obj\Debug\srcs\camera.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\camera2.c -o obj\Debug\srcs\camera2.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\camera3.c -o obj\Debug\srcs\camera3.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\checks.c -o obj\Debug\srcs\checks.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\draw.c -o obj\Debug\srcs\draw.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\draw2.c -o obj\Debug\srcs\draw2.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\draw3.c -o obj\Debug\srcs\draw3.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\keycode.c -o obj\Debug\srcs\keycode.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\main.c -o obj\Debug\srcs\main.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\math.c -o obj\Debug\srcs\math.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\matrix_op.c -o obj\Debug\srcs\matrix_op.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\matrix_op2.c -o obj\Debug\srcs\matrix_op2.o
C:\MinGW\bin\mingw32-gcc.exe -Wall -Wextra -Werror -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\srcs\parsing.c -o obj\Debug\srcs\parsing.o

C:\MinGW\bin\mingw32-g++.exe -LC:\MinGW\lib -o bin\Debug\Wolf3d.exe obj\Debug\libft\ft_atoi.o obj\Debug\libft\ft_atoi_base.o obj\Debug\libft\ft_bzero.o obj\Debug\libft\ft_isalnum.o obj\Debug\libft\ft_isalpha.o obj\Debug\libft\ft_isascii.o obj\Debug\libft\ft_isdigit.o obj\Debug\libft\ft_isprint.o obj\Debug\libft\ft_iswhitespace.o obj\Debug\libft\ft_itoa.o obj\Debug\libft\ft_lst_to_str.o obj\Debug\libft\ft_lst_to_strn.o obj\Debug\libft\ft_lstadd.o obj\Debug\libft\ft_lstadd_end.o obj\Debug\libft\ft_lstdel.o obj\Debug\libft\ft_lstdelone.o obj\Debug\libft\ft_lstiter.o obj\Debug\libft\ft_lstmap.o obj\Debug\libft\ft_lstnew.o obj\Debug\libft\ft_mem.o obj\Debug\libft\ft_memalloc.o obj\Debug\libft\ft_memccpy.o obj\Debug\libft\ft_memchr.o obj\Debug\libft\ft_memcmp.o obj\Debug\libft\ft_memcpy.o obj\Debug\libft\ft_memdel.o obj\Debug\libft\ft_memmove.o obj\Debug\libft\ft_memset.o obj\Debug\libft\ft_print_memory.o obj\Debug\libft\ft_put_addr.o obj\Debug\libft\ft_putchar.o obj\Debug\libft\ft_putchar_fd.o obj\Debug\libft\ft_putendl.o obj\Debug\libft\ft_putendl_fd.o obj\Debug\libft\ft_putnbr.o obj\Debug\libft\ft_putnbr_fd.o obj\Debug\libft\ft_putstr.o obj\Debug\libft\ft_putstr_fd.o obj\Debug\libft\ft_puttab.o obj\Debug\libft\ft_realloc.o obj\Debug\libft\ft_skipspaces.o obj\Debug\libft\ft_strcat.o obj\Debug\libft\ft_strchr.o obj\Debug\libft\ft_strclr.o obj\Debug\libft\ft_strcmp.o obj\Debug\libft\ft_strcpy.o obj\Debug\libft\ft_strdel.o obj\Debug\libft\ft_strdup.o obj\Debug\libft\ft_strequ.o obj\Debug\libft\ft_striter.o obj\Debug\libft\ft_striteri.o obj\Debug\libft\ft_strjoin.o obj\Debug\libft\ft_strlcat.o obj\Debug\libft\ft_strlcpy.o obj\Debug\libft\ft_strlen.o obj\Debug\libft\ft_strmap.o obj\Debug\libft\ft_strmapi.o obj\Debug\libft\ft_strncat.o obj\Debug\libft\ft_strncmp.o obj\Debug\libft\ft_strncpy.o obj\Debug\libft\ft_strnequ.o obj\Debug\libft\ft_strnew.o obj\Debug\libft\ft_strnstr.o obj\Debug\libft\ft_strrchr.o obj\Debug\libft\ft_strsplit.o obj\Debug\libft\ft_strstr.o obj\Debug\libft\ft_strsub.o obj\Debug\libft\ft_strtol.o obj\Debug\libft\ft_strtoll.o obj\Debug\libft\ft_strtrim.o obj\Debug\libft\ft_tolower.o obj\Debug\libft\ft_toupper.o obj\Debug\libft\get_next_line.o obj\Debug\srcs\camera.o obj\Debug\srcs\camera2.o obj\Debug\srcs\camera3.o obj\Debug\srcs\checks.o obj\Debug\srcs\draw.o obj\Debug\srcs\draw2.o obj\Debug\srcs\draw3.o obj\Debug\srcs\keycode.o obj\Debug\srcs\main.o obj\Debug\srcs\math.o obj\Debug\srcs\matrix_op.o obj\Debug\srcs\matrix_op2.o obj\Debug\srcs\parsing.o   -lmingw32 -lSDL2main -lSDL2.dll -luser32 -lgdi32 -lwinmm -ldxguid

D:\Work\wolf3d\bin\Debug\Wolf3d.exe D:\Work\wolf3d\test.map