mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_atoi.c -o ..\obj\Debug\libft\ft_atoi.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_atoi_base.c -o ..\obj\Debug\libft\ft_atoi_base.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_bzero.c -o ..\obj\Debug\libft\ft_bzero.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_isalnum.c -o ..\obj\Debug\libft\ft_isalnum.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_isalpha.c -o ..\obj\Debug\libft\ft_isalpha.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_isascii.c -o ..\obj\Debug\libft\ft_isascii.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_isdigit.c -o ..\obj\Debug\libft\ft_isdigit.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_isprint.c -o ..\obj\Debug\libft\ft_isprint.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_iswhitespace.c -o ..\obj\Debug\libft\ft_iswhitespace.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_itoa.c -o ..\obj\Debug\libft\ft_itoa.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_lst_to_str.c -o ..\obj\Debug\libft\ft_lst_to_str.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_lst_to_strn.c -o ..\obj\Debug\libft\ft_lst_to_strn.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_lstadd.c -o ..\obj\Debug\libft\ft_lstadd.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_lstadd_end.c -o ..\obj\Debug\libft\ft_lstadd_end.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_lstdel.c -o ..\obj\Debug\libft\ft_lstdel.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_lstdelone.c -o ..\obj\Debug\libft\ft_lstdelone.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_lstiter.c -o ..\obj\Debug\libft\ft_lstiter.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_lstmap.c -o ..\obj\Debug\libft\ft_lstmap.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_lstnew.c -o ..\obj\Debug\libft\ft_lstnew.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_mem.c -o ..\obj\Debug\libft\ft_mem.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_memalloc.c -o ..\obj\Debug\libft\ft_memalloc.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_memccpy.c -o ..\obj\Debug\libft\ft_memccpy.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_memchr.c -o ..\obj\Debug\libft\ft_memchr.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_memcmp.c -o ..\obj\Debug\libft\ft_memcmp.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_memcpy.c -o ..\obj\Debug\libft\ft_memcpy.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_memdel.c -o ..\obj\Debug\libft\ft_memdel.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_memmove.c -o ..\obj\Debug\libft\ft_memmove.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_memset.c -o ..\obj\Debug\libft\ft_memset.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_print_memory.c -o ..\obj\Debug\libft\ft_print_memory.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_put_addr.c -o ..\obj\Debug\libft\ft_put_addr.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_putchar.c -o ..\obj\Debug\libft\ft_putchar.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_putchar_fd.c -o ..\obj\Debug\libft\ft_putchar_fd.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_putendl.c -o ..\obj\Debug\libft\ft_putendl.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_putendl_fd.c -o ..\obj\Debug\libft\ft_putendl_fd.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_putnbr.c -o ..\obj\Debug\libft\ft_putnbr.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_putnbr_fd.c -o ..\obj\Debug\libft\ft_putnbr_fd.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_putstr.c -o ..\obj\Debug\libft\ft_putstr.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_putstr_fd.c -o ..\obj\Debug\libft\ft_putstr_fd.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_puttab.c -o ..\obj\Debug\libft\ft_puttab.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_realloc.c -o ..\obj\Debug\libft\ft_realloc.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_skipspaces.c -o ..\obj\Debug\libft\ft_skipspaces.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strcat.c -o ..\obj\Debug\libft\ft_strcat.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strchr.c -o ..\obj\Debug\libft\ft_strchr.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strclr.c -o ..\obj\Debug\libft\ft_strclr.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strcmp.c -o ..\obj\Debug\libft\ft_strcmp.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strcpy.c -o ..\obj\Debug\libft\ft_strcpy.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strdel.c -o ..\obj\Debug\libft\ft_strdel.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strdup.c -o ..\obj\Debug\libft\ft_strdup.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strequ.c -o ..\obj\Debug\libft\ft_strequ.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_striter.c -o ..\obj\Debug\libft\ft_striter.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_striteri.c -o ..\obj\Debug\libft\ft_striteri.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strjoin.c -o ..\obj\Debug\libft\ft_strjoin.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strlcat.c -o ..\obj\Debug\libft\ft_strlcat.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strlcpy.c -o ..\obj\Debug\libft\ft_strlcpy.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strlen.c -o ..\obj\Debug\libft\ft_strlen.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strmap.c -o ..\obj\Debug\libft\ft_strmap.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strmapi.c -o ..\obj\Debug\libft\ft_strmapi.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strncat.c -o ..\obj\Debug\libft\ft_strncat.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strncmp.c -o ..\obj\Debug\libft\ft_strncmp.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strncpy.c -o ..\obj\Debug\libft\ft_strncpy.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strnequ.c -o ..\obj\Debug\libft\ft_strnequ.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strnew.c -o ..\obj\Debug\libft\ft_strnew.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strnstr.c -o ..\obj\Debug\libft\ft_strnstr.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strrchr.c -o ..\obj\Debug\libft\ft_strrchr.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strsplit.c -o ..\obj\Debug\libft\ft_strsplit.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strstr.c -o ..\obj\Debug\libft\ft_strstr.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strsub.c -o ..\obj\Debug\libft\ft_strsub.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strtol.c -o ..\obj\Debug\libft\ft_strtol.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strtoll.c -o ..\obj\Debug\libft\ft_strtoll.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_strtrim.c -o ..\obj\Debug\libft\ft_strtrim.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_tolower.c -o ..\obj\Debug\libft\ft_tolower.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\ft_toupper.c -o ..\obj\Debug\libft\ft_toupper.o
mingw32-gcc.exe -Wall -g -IC:\MinGW\include -Iincludes -c D:\Work\wolf3d\libft\get_next_line.c -o ..\obj\Debug\libft\get_next_line.o
